#!/usr/bin/env bash
#configure Nginx server
DUMMY="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" 
mkdir -p /var/www/html/
apt -y update
apt -y install nginx-full
echo "Holberton School for the win!" > /var/www/html/index.html
sudo sed -i "30i $DUMMY" /etc/nginx/sites-available/default 
service nginx restart
