#!/usr/bin/env bash
# Serve full nginx server
DUMMY="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
MISTAKE_404="error_page 404 = /not_found_page_404.html;"
mkdir -p /var/www/html/
touch /var/www/html/not_found_page_404.html
apt -y update
apt -y install nginx-full
echo "Ceci n'est pas une page" > /var/www/html/not_found_page_404.html
echo "Holberton School for the win!" > /var/www/html/index.html
sudo sed -i "30i $DUMMY" /etc/nginx/sites-available/default
sudo sed -i "19i $MISTAKE_404" /etc/nginx/sites-available/default
service nginx restart
