#!/usr/bin/env bash
# Print loop with conditions and else
n=1
while [ $n -lt 11 ]
do
	if [ $n -eq 4 ]
	then
		echo "bad luck"
	elif [ $n -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton school"
	fi
	((n++))
done
