#!/usr/bin/env bash
n=1
while [ $n -lt 21 ]
do
	if [ $n -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $n -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $n -eq 17 ]
	then
		echo "bad luck from Italy"
	else
		echo $n
	fi
	((n++))
done
